title: Aiden's Blog
description: Personal thoughts on tech, code, and everything in between.
url: "https://aidencullo.github.io"
baseurl: "/aidensroom.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
