title: Aiden's Personal Blog
description: Personal thoughts on tech, code, and everything in between.
url: "https://blog.aidencullo.com"
baseurl: ""

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
